"""Version-gated, Python-only QAIRT 2.49 adapters."""

from .adapter import QairtSdkAdapter
from .errors import (
    ExperimentalFeatureError,
    NativeKvConfigError,
    QairtAdapterError,
    QairtConfigurationError,
    QairtPreflightError,
    QairtSdkImportError,
)
from .native_kv import (
    NATIVE_KV_DATA_FORMAT,
    audit_native_kv_config,
    build_native_kv_config,
    require_native_kv_audit,
)
from .preflight import (
    PINNED_DSP_ARCH,
    PINNED_PYTHON,
    PINNED_QAIRT_BUILD_ID,
    PINNED_QAIRT_VERSION,
    PINNED_SOC_MODEL,
    PINNED_TARGET_SOC,
    PINNED_UBUNTU_VERSION,
    PreflightChecker,
    PreflightSpec,
    require_preflight,
)
from .types import (
    BuildResult,
    CompiledContextArtifact,
    ConvertedModelArtifact,
    GenAIAttachedModel,
    GenAIContainerBuildResult,
    GenAIRawSliceArtifact,
    IssueSeverity,
    ModelVariantArtifact,
    NativeKvAuditReport,
    NativeKvGraphExpectation,
    PreflightIssue,
    PreflightReport,
    ProfileResult,
    QuantizedModelArtifact,
    Qwen35ValidationEvidence,
    Qwen35DerivationValidation,
    Qwen35RuntimeValidationRequest,
    Qwen35RuntimeValidationResult,
    TransformedSliceArtifact,
)

__all__ = [
    "BuildResult",
    "CompiledContextArtifact",
    "ConvertedModelArtifact",
    "ExperimentalFeatureError",
    "GenAIAttachedModel",
    "GenAIContainerBuildResult",
    "GenAIRawSliceArtifact",
    "IssueSeverity",
    "ModelVariantArtifact",
    "NATIVE_KV_DATA_FORMAT",
    "NativeKvAuditReport",
    "NativeKvConfigError",
    "NativeKvGraphExpectation",
    "PINNED_DSP_ARCH",
    "PINNED_PYTHON",
    "PINNED_QAIRT_BUILD_ID",
    "PINNED_QAIRT_VERSION",
    "PINNED_SOC_MODEL",
    "PINNED_TARGET_SOC",
    "PINNED_UBUNTU_VERSION",
    "PreflightChecker",
    "PreflightIssue",
    "PreflightReport",
    "PreflightSpec",
    "ProfileResult",
    "QairtAdapterError",
    "QairtConfigurationError",
    "QairtPreflightError",
    "QairtSdkAdapter",
    "QairtSdkImportError",
    "QuantizedModelArtifact",
    "Qwen35ValidationEvidence",
    "Qwen35DerivationValidation",
    "Qwen35RuntimeValidationRequest",
    "Qwen35RuntimeValidationResult",
    "TransformedSliceArtifact",
    "audit_native_kv_config",
    "build_native_kv_config",
    "require_native_kv_audit",
    "require_preflight",
]
