"""Model-family configuration, ONNX inspection, and graph split contracts."""

from .config import FamilyConfigGenerator, GeneratedFamilyConfig
from .inspector import InitializerInfo, NodeInfo, OnnxInspector, OnnxModelInfo, TensorInfo
from .presets import (
    PRESET_REGISTRY,
    GENAI_OUTPUT_LAYOUT,
    LOW_LEVEL_OUTPUT_LAYOUT,
    QWEN3_5_OMNI_PRESET,
    QWEN3_5_OMNI_THINKER_PRESET,
    QWEN3_5_PRESET,
    QWEN3_DENSE_PRESET,
    QWEN3_MOE_PRESET,
    QWEN3_VL_PRESET,
    VIT_PRESET,
    ResolvedWorkflow,
    family_for_preset,
    get_preset,
    resolve_workflow,
    to_build_spec,
)
from .profiles import (
    FAMILY_PROFILES,
    QWEN3_5,
    QWEN3_5_OMNI,
    QWEN3_DENSE,
    QWEN3_MOE,
    QWEN3_VL,
    AutoArPolicy,
    FamilyId,
    FamilyProfile,
    MhaStartPointSpec,
    QairtFactorySupport,
    get_family_profile,
    resolve_family_profile,
    validate_weight_sharing_sources,
)
from .sku import capture_sku, merge_sku
from .split_plan import SliceKind, SliceSpec, SplitPlan, build_split_plan

__all__ = [
    "AutoArPolicy",
    "FAMILY_PROFILES",
    "FamilyConfigGenerator",
    "FamilyId",
    "FamilyProfile",
    "GeneratedFamilyConfig",
    "GENAI_OUTPUT_LAYOUT",
    "InitializerInfo",
    "MhaStartPointSpec",
    "NodeInfo",
    "OnnxInspector",
    "OnnxModelInfo",
    "PRESET_REGISTRY",
    "LOW_LEVEL_OUTPUT_LAYOUT",
    "QWEN3_5",
    "QWEN3_5_OMNI",
    "QWEN3_5_OMNI_PRESET",
    "QWEN3_5_OMNI_THINKER_PRESET",
    "QWEN3_5_PRESET",
    "QWEN3_DENSE",
    "QWEN3_DENSE_PRESET",
    "QWEN3_MOE",
    "QWEN3_MOE_PRESET",
    "QWEN3_VL",
    "QWEN3_VL_PRESET",
    "QairtFactorySupport",
    "ResolvedWorkflow",
    "SliceKind",
    "SliceSpec",
    "SplitPlan",
    "TensorInfo",
    "VIT_PRESET",
    "build_split_plan",
    "capture_sku",
    "family_for_preset",
    "get_family_profile",
    "get_preset",
    "merge_sku",
    "resolve_family_profile",
    "resolve_workflow",
    "to_build_spec",
    "validate_weight_sharing_sources",
]
